---
- name: "NODEJS | Ensure nodejs directory for downloadable exists"
  ansible.builtin.file:
    path: /tmp/nodejs
    state: directory
    mode: "0755"

- name: "NODEJS | Download nodejs"
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/setup_lts.x"
    dest: /tmp/nodejs/nodesource_setup.sh
    mode: "0644"
    force: true

- name: "NODEJS | Extract nodejs and prepare for installation"
  ansible.builtin.file: 
    path: /tmp/nodejs/nodesource_setup.sh
    mode: "0755"
  become: true

- name: "NODEJS | Install nodejs"
  ansible.builtin.apt: 
    name: nodejs
  become: true
  notify:
    - Remove extracted nodejs directory
