---
- name: "Uninstall APT fzf"
  ansible.builtin.apt:
    name: fzf
    state: absent
  become: true

- name: "Clone Latest Version"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ ansible_user_dir }}/.fzf"
  notify: "Install FZF"

- name: "Dependencies"
  ansible.builtin.apt:
    name: fd-find
    state: present
  become: true
