---
- name: "Tmux | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    update: no
  become: true

- name: "Tmux | {{ ansible_distribution }} | Install tmux"
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: "Tmux | {{ ansible_distribution }} | Install tmux plugins"
  ansible.builtin.shell: |
    tmux new-session -d -s temp_session
    tmux run-shell "~/.tmux/plugins/tpm/scripts/install_plugins.sh"
    tmux kill-session -t temp_session
  become: false
