---
- name: "{{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: "{{ ansible_distribution }} | Install via snap"
  ansible.builtin.shell:
    cmd: snap install nvim --stable --classic
  become: true
